# Inspired by github.com/Chealion/yycbike

name: eco_counter_bot

on:
    workflow_dispatch:
    
    schedule:
      - cron: "0 6 * * *" #runs at 06:00 UTC everyday, 08:00 LU time 

jobs:
  eco_counter_bot:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          # act wants a specific version while GitHub is happy with 3.x
          python-version: '3.9.6'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run the script
        run: |
          python -m eco_counter_bot
        env:
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
